---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-owasp-zap.yml"

.services:
  services:
    - name: $CONTAINER_TEST_IMAGE
      alias: csp-reports
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update curl
  variables:
    GIT_STRATEGY: none
  dependencies: []

variables:
  CI_DEBUG_SERVICES: "true"
  CSP_REPORTS_SCHEME: "http"
  CSP_REPORTS_PORT: "9999"
  OWASP_ZAP_TARGET: "${CSP_REPORTS_SCHEME}://target:${CSP_REPORTS_PORTT}"

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean

CSP Reports:
  stage: Test
  extends: .services
  script:
    - curl -f --connect-timeout 60 -d '{"key1":"value1"}' -H "Content-Type:application/csp-report" -X POST ${CSP_REPORTS_SCHEME}://csp-reports:${CSP_REPORTS_PORT}
